In [1]:
import numpy as np

In [2]:
s_z = np.array([[1, 0], [0, -1]])
identity = np.array([[1, 0], [0, 1]])

In [3]:
z_1 = np.kron(s_z, identity)
z_1

array([[ 1,  0,  0,  0],
       [ 0,  1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [4]:
z_2 = np.kron(identity, s_z)
z_2

array([[ 1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0,  1,  0],
       [ 0,  0,  0, -1]])

In [5]:
prod_1 = np.kron(s_z, s_z)
prod_1

array([[ 1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0,  1]])

In [6]:
prod_2 = np.kron(identity, identity)
prod_2

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [7]:
z_1 @ z_2

array([[ 1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0,  1]])