In [1]:
import numpy as np
import scipy

In [2]:
class MeasurementOperator:
    def __init__(self, density_matrix: np.array):
        self.density_matrix = density_matrix
        self.eigenvalues, self.eigenstates = scipy.linalg.eig(density_matrix)

    def get_amplitudes(self, quantum_state: np.array) -> np.array:
        quantum_state = np.divide(quantum_state, scipy.linalg.norm(quantum_state))
        return self.eigenstates @ quantum_state @ self.eigenstates.T

    def get_probabilities(self, quantum_state: np.array) -> np.array:
        return self.get_amplitudes(quantum_state=quantum_state) ** 2

    def summary(self) -> None:
        pass

In [3]:
density_matrix = [[1, 0], [0, -1]]
mo = MeasurementOperator(density_matrix)

In [4]:
mo.get_probabilities([1, 1])

array([0.5, 0.5])

In [5]:
factor = np.divide(np.sqrt(2), 1 + np.sqrt(2))
e_1 = factor * np.array([[0, 0], [0, 1]])
e_2 = factor * np.array([[1, -1], [-1, 1]])
e_3 = np.array([[1, 0], [0, 1]]) - e_1 - e_2

In [6]:
density_matrix = 1 * e_1 + 2 * e_2 + 3 * e_3
mo = MeasurementOperator(density_matrix)
mo.density_matrix

array([[2.41421356, 0.58578644],
       [0.58578644, 1.24264069]])

In [7]:
mo.get_probabilities([1, 0])

array([0.5, 0.5])

In [8]:
mo.get_probabilities([1, 1])

array([7.41362644e-35, 1.00000000e+00])